export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const STORE_USER_ON_SIGNUP_SUCCESS = 'STORE_USER_ON_SIGNUP_SUCCESS';
export const STORE_USER_ON_SIGNUP_FAIL = 'STORE_USER_ON_SIGNUP_FAIL';

export const SAVE_QUESTION = 'SAVE_QUESTION';
export const SAVE_QUESTION_SUCCESS = 'SAVE_QUESTION_SUCCESS';
export const SAVE_QUESTION_FAIL = 'SAVE_QUESTION_FAIL';

export const SAVE_QUESTION_TO_USER = 'SAVE_QUESTION_TO_USER';
export const SAVE_QUESTION_TO_USER_SUCCESS = 'SAVE_QUESTION_TO_USER_SUCCESS';
export const SAVE_QUESTION_TO_USER_FAIL = 'SAVE_QUESTION_TO_USER_FAIL';

export const SAVE_ANSWER = 'SAVE_ANSWER';
export const SAVE_ANSWER_SUCCESS = 'SAVE_ANSWER_SUCCESS';
export const SAVE_ANSWER_FAIL = 'SAVE_ANSWER_FAIL';


export const SAVE_ANSWER_TO_USER = 'SAVE_ANSWER_TO_USER';
export const SAVE_ANSWER_TO_USER_SUCCESS = 'SAVE_ANSWER_TO_USER_SUCCESS';
export const SAVE_ANSWER_TO_USER_FAIL = 'SAVE_ANSWER_TO_USER_FAIL';


export const SAVE_COMMENT = 'SAVE_COMMENT';
export const SAVE_COMMENT_SUCCESS = 'SAVE_COMMENT_SUCCESS';
export const SAVE_COMMENT_FAIL = 'SAVE_COMMENT_FAIL';


export const SAVE_COMMENT_TO_USER = 'SAVE_COMMENT_TO_USER';
export const SAVE_COMMENT_TO_USER_SUCCESS = 'SAVE_COMMENT_TO_USER_SUCCESS';
export const SAVE_COMMENT_TO_USER_FAIL = 'SAVE_COMMENT_TO_USER_FAIL';

export const INCREMENT_INSIGHTFUL = 'INCREMENT_INSIGHTFUL';
export const INCREMENT_INSIGHTFUL_SUCCESS = 'INCREMENT_INSIGHTFUL_SUCCESS';
export const INCREMENT_INSIGHTFUL_FAIL = 'INCREMENT_INSIGHTFUL_FAIL';

export const NOTIFICATION_DELETE = 'NOTIFICATION_DELETE';
export const NOTIFICATION_DELETE_SUCCESS = 'NOTIFICATION_DELETE_SUCCESS';
export const NOTIFICATION_DELETE_FAIL = 'NOTIFICATION_DELETE_FAIL';



