export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const STORE_USER_ON_SIGNUP_SUCCESS = 'STORE_USER_ON_SIGNUP_SUCCESS';
export const STORE_USER_ON_SIGNUP_FAIL = 'STORE_USER_ON_SIGNUP_FAIL';

export const SAVE_QUESTION = 'SAVE_QUESTION';
export const SAVE_QUESTION_SUCCESS = 'SAVE_QUESTION_SUCCESS';
export const SAVE_QUESTION_FAIL = 'SAVE_QUESTION_FAIL';

export const SAVE_QUESTION_TO_USER = 'SAVE_QUESTION_TO_USER';
export const SAVE_QUESTION_TO_USER_SUCCESS = 'SAVE_QUESTION_TO_USER_SUCCESS';
export const SAVE_QUESTION_TO_USER_FAIL = 'SAVE_QUESTION_TO_USER_FAIL';



